"use client";

import type { StoredReport } from "@/lib/report/service";
import { Check, Copy } from "lucide-react";
import { useState } from "react";

function buildMarkdown(report: StoredReport): string {
  const r = report.payload;
  const date = new Date(report.createdAt).toLocaleDateString("en-GB", {
    day: "numeric", month: "short", year: "numeric",
  });

  const lines: string[] = [
    `# FPL//AI Brief — GW${report.gameweek}`,
    `> Built ${date} · Engine: ${report.engine} · Confidence: ${r.confidence}`,
    "",
  ];

  if (r.headline) {
    lines.push(`**${r.headline}**`, "");
  }

  lines.push(
    "## ⚜️ Captain Pick",
    `**${r.captain_suggestion.player}**`,
    r.captain_suggestion.reasoning,
    "",
    "## 🔵 Vice-Captain",
    `**${r.vice_captain_suggestion.player}**`,
    r.vice_captain_suggestion.reasoning,
    "",
  );

  if (r.transfer_suggestions.length > 0) {
    lines.push("## 🔄 Transfers");
    r.transfer_suggestions.forEach((t, i) => {
      const cost = t.cost_delta > 0
        ? `+£${t.cost_delta.toFixed(1)}m`
        : `−£${Math.abs(t.cost_delta).toFixed(1)}m`;
      const gw = t.gameweek ? `GW${t.gameweek}` : "Current GW";
      lines.push(
        `**${gw} — Move ${i + 1}** (${cost})`,
        `OUT: ${t.out} → IN: ${t.in}`,
        t.reasoning,
        "",
      );
    });
  } else {
    lines.push("## 🔄 Transfers", "Hold. No responsible moves found.", "");
  }

  if (r.dos.length) {
    lines.push("## ✅ Do", ...r.dos.map((d) => `- ${d}`), "");
  }

  if (r.donts.length) {
    lines.push("## ❌ Don't", ...r.donts.map((d) => `- ${d}`), "");
  }

  lines.push("---", "*Generated by FPL//AI — unofficial, public data only.*");
  return lines.join("\n");
}

export function ExportBrief({ report }: { report: StoredReport }) {
  const [state, setState] = useState<"idle" | "copied" | "error">("idle");

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(buildMarkdown(report));
      setState("copied");
      setTimeout(() => setState("idle"), 2000);
    } catch {
      setState("error");
      setTimeout(() => setState("idle"), 2000);
    }
  };

  return (
    <div className="relative">
      <button
        onClick={copy}
        className="group flex items-center gap-2 rounded-xl border hairline px-3.5 py-2 font-mono text-[10px] uppercase tracking-[0.18em] text-mute transition-all hover:border-glow/50 hover:text-glow"
        title="Copy brief as markdown"
        aria-label="Copy brief as markdown to clipboard"
      >
        {state === "copied" ? (
          <Check className="h-3.5 w-3.5 text-neon" />
        ) : (
          <Copy className="h-3.5 w-3.5" />
        )}
        {state === "copied" ? "Copied!" : "Export"}
      </button>

      {/* Toast */}
      {state === "copied" && (
        <span
          className="toast-in pointer-events-none absolute -bottom-8 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-lg bg-neon/20 px-3 py-1 font-mono text-[10px] text-neon border border-neon/30"
          aria-live="polite"
        >
          Copied to clipboard ✓
        </span>
      )}
    </div>
  );
}
